### ISSUE TITLE
Thank you :)

### ISSUE THREAD

**Issue by ZeroDot1** [parseword/nolovia#1]
Thank you for using the CoinBlockerLists.

https://github.com/ZeroDot1/CoinBlockerLists/commit/2758253a5e4ff8741516a6ae855e7bbcd52ebbb2

https://github.com/ZeroDot1/CoinBlockerLists#coinblockerlists-is-used-in-nolovia-httpsgithubcomparsewordnolovia

**Comment by parseword** [comment]
And thanks for compiling them, cryptojacking is getting to be a real problem!
