### ISSUE TITLE
officeclient.microsoft.com ecs.office.com

### ISSUE THREAD

**Issue by p1r473** [parseword/nolovia#7]
These are valid Office domains and not malicious 
@parseword

**Comment by parseword** [comment]
Hi, thanks for catching these, I removed `officeclient.microsoft.com`. Offhand I don't see where `ecs.office.com` would be getting blocked; it follows a chain of several CNAMEs but it doesn't look like any of them are listed in any of nolovia's bundled files:

    $ dig ecs.office.com
    
    ; <<>> DiG 9.16.22 <<>> ecs.office.com
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30854
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1
    
    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 1232
    ; COOKIE: 3ec073914ed277e60100000061809d85b7bd7d2e6b2d3253 (good)
    ;; QUESTION SECTION:
    ;ecs.office.com.                        IN      A
    
    ;; ANSWER SECTION:
    ecs.office.com.         300     IN      CNAME   ecs.office.trafficmanager.net.
    ecs.office.trafficmanager.net. 60 IN    CNAME   s-0005-office.config.skype.com.
    s-0005-office.config.skype.com. 3571 IN CNAME   ecs-office.s-0005.s-msedge.net.
    ecs-office.s-0005.s-msedge.net. 211 IN  CNAME   s-0005.s-msedge.net.
    s-0005.s-msedge.net.    211     IN      A       52.113.194.132

**Comment by p1r473** [comment]
Thanks, must have been an error on my end regarding ecs.office.com
